---
name: Build MPI Wrapper Package

concurrency:
  group: ${{ startsWith(github.ref_name, 'main') && format('unique-{0}', github.run_id) || format('ci-gh-mpi-{0}-from-{1}', github.event_name, github.ref_name) }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"
      - "main"

jobs:
  build:
    uses:
      ./.github/workflows/gh-mpi.yml
