---
on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      build-type:
        type: string
        required: true
      python-version:
        type: string
        required: true
      target-device:
        type: string
        required: true
      upload-enabled:
        type: boolean
        required: true
      network:
        type: string
        required: true
      refname:
        required: true
        type: string
      default-branch:
        required: true
        type: string

jobs:
  Build_Profiler:
    if: ${{ github.repository_owner == 'nv-legate' }}
    uses:
      nv-legate/legate-gh-ci/.github/workflows/gh-build.yml@use_nv_proxy_cache
    with:
      client-repo: ${{ github.event.repository.name }}
      target-device: ${{ inputs.target-device }}
      runs-on: ${{ (inputs.platform == 'linux' && 'linux-amd64-cpu16') || (inputs.platform == 'linux-aarch64' && 'linux-arm64-cpu16') || (inputs.platform == 'mac' && 'macos-latest') }}
      build-has-tests: ${{ inputs.upload-enabled == false }}
      build-type: ${{ inputs.build-type }}
      use-container: ${{ inputs.platform == 'linux' || inputs.platform == 'linux-aarch64'}}
      platform: ${{ inputs.platform }}
      dependencies-file: ""
      legate-gh-ci-tag: "use_nv_proxy_cache"
      build-mode: ""
      upload-enabled: ${{ inputs.upload-enabled }}
      python-version: ${{ inputs.python-version }}
      network: ${{ inputs.network }}
      setup-python-proxy-cache: true
    secrets: inherit

  Upload_Profiler:
    needs: Build_Profiler
    name: Upload Legate Profiler
    uses:
      nv-legate/legate-gh-ci/.github/workflows/gh-upload.yml@use_nv_proxy_cache
    with:
      build-mode: ""
      build-type: ${{ inputs.build-type }}
      client-repo: ${{ github.event.repository.name }}
      build-has-tests: ${{ inputs.upload-enabled == false }}
      legate-gh-ci-tag: "use_nv_proxy_cache"
      name: Upload package to Anaconda
      network: ${{ inputs.network }}
      pkgSubString: "legate-profiler"
      platform: ${{ inputs.platform }}
      python-version: ${{ inputs.python-version }}
      repos-Root: "legate-profiler"
      target-device: ${{ inputs.target-device }}
      upload-action: "upload-package-Anaconda"
      upload-enabled: ${{ inputs.upload-enabled }}
      refname: ${{ inputs.refname }}
      default-branch: ${{ inputs.default-branch }}
    secrets: inherit
